CREATE TABLE courses (
  id INT AUTO_INCREMENT PRIMARY KEY,
  course_type INT NOT NULL,
  course_name VARCHAR(255) NOT NULL,
  years INT NOT NULL,
  semesters INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by INTEGER,
  updated_by INTEGER
);