CREATE TABLE saas_student_detail (
  student_id INT NOT NULL PRIMARY KEY,
  course_id INT NOT NULL,
  year_id INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  father_name VARCHAR(255),
  mother_name VARCHAR(255),
  mobile_number VARCHAR(15),
  dob DATE,
  email VARCHAR(255),
  category VARCHAR(50),
  ews ENUM('Yes', 'No'),
  nationality VARCHAR(100),
  religion VARCHAR(100),
  residence_type VARCHAR(100),
  parent_annual_income INT,
  permanent_address TEXT,
  pincode VARCHAR(10),
  country VARCHAR(100),
  state VARCHAR(100),
  district VARCHAR(100),
  aadhar_number VARCHAR(12),
  guardian_mobile_number VARCHAR(15),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by INTEGER,
  updated_by INTEGER
);
